"""Initial Migration

Revision ID: 13345523d3ef
Revises: 
Create Date: 2023-11-22 15:45:49.476848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13345523d3ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
