"""adding profile-pic field

Revision ID: 69998a70ebdf
Revises: b552124ef36d
Create Date: 2023-11-27 15:22:48.722903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69998a70ebdf'
down_revision = 'b552124ef36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
