"""date_post to date_posted

Revision ID: e2127e94237c
Revises: 12be70e2862a
Create Date: 2023-11-23 14:55:44.918572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2127e94237c'
down_revision = '12be70e2862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_post', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
